How to apply dataset filter expression while get parameter selection …
eclipse-birt/birt pull request #2005
Opened 2024-12-09 09:05 UTC by chille716

…list? #1993

I added a boolean to enable/disable the normal data engine flow mode to apply filter expressions in datasets.

2024-12-09 09:30 UTC, merks reviewed
Wouldn't it be more general to have a getting and setting that returns a value of type DataEngineFlowMode?

2024-12-09 09:38 UTC, chille716 commented
@merks I was not sure about it... that's why I implemented it microinversively. Can't find any places where the other modes (IV, DATA_EXTRACTION) will be used.  But if it useful to set these modes at this place, then i can change it.

2024-12-09 10:34 UTC, merks commented
FYI 

@speckyspooky  @wimjongman 

I don't really know the APIs well.  You're right that the other enumerators appear unused.  So I'll wait for other folks to comment.   Note that adding methods to API breaks the API so whatever we do here,  I think it would be better to define default methods in the interface, which means the mock class needs no changes....

2024-12-09 16:29 UTC, speckyspooky requested changes
Please add there default-methods to avoid broken API

2024-12-09 16:29 UTC, speckyspooky commented on engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IGetParameterDefinitionTask.java
> +	void setNormalFlowModeEnabled(boolean normalFlowModeEnabled);
Add "default"-method for the new method - PR #1970, see IWordWriter.

![grafik](https://github.com/user-attachments/assets/641302a4-ea3e-4171-99b3-73e65e3553a5)

2024-12-09 16:29 UTC, speckyspooky commented on engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IGetParameterDefinitionTask.java
> +	boolean isNormalFlowModeEnabled();
Add "default"-method for the new method - PR #1970, see IWordWriter.

2024-12-10 19:28 UTC, speckyspooky approved these changes
Looks good

2024-12-11 05:14 UTC, merged